# Generated by Django 5.2.4 on 2025-08-24 02:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_notifications_user_privacy_user_theme'),
    ]

    operations = [
        migrations.CreateModel(
            name='EAAuthToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('algorithm_id', models.CharField(help_text='Unique identifier for the EA/algorithm', max_length=100)),
                ('name', models.CharField(help_text='Human-readable name for the EA', max_length=200)),
                ('token', models.CharField(help_text='The actual token string', max_length=128, unique=True)),
                ('token_hash', models.CharField(help_text='SHA256 hash of the token for security', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(help_text='Token expiration time')),
                ('is_active', models.BooleanField(default=True)),
                ('permissions', models.JSONField(default=dict, help_text='Specific permissions for this EA token')),
                ('settings', models.JSONField(default=dict, help_text='EA-specific settings and configuration')),
                ('connection_count', models.IntegerField(default=0, help_text='Number of times this token has been used to connect')),
                ('last_ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ea_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'EA Authentication Token',
                'verbose_name_plural': 'EA Authentication Tokens',
            },
        ),
        migrations.CreateModel(
            name='EAConnectionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('disconnected_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('connection_duration', models.DurationField(blank=True, null=True)),
                ('disconnect_reason', models.CharField(blank=True, max_length=100)),
                ('messages_sent', models.IntegerField(default=0)),
                ('messages_received', models.IntegerField(default=0)),
                ('trades_reported', models.IntegerField(default=0)),
                ('errors_encountered', models.IntegerField(default=0)),
                ('ea_token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connection_logs', to='authentication.eaauthtoken')),
            ],
            options={
                'verbose_name': 'EA Connection Log',
                'verbose_name_plural': 'EA Connection Logs',
            },
        ),
        migrations.AddIndex(
            model_name='eaauthtoken',
            index=models.Index(fields=['token_hash'], name='authenticat_token_h_484020_idx'),
        ),
        migrations.AddIndex(
            model_name='eaauthtoken',
            index=models.Index(fields=['user', 'is_active'], name='authenticat_user_id_b6ed4c_idx'),
        ),
        migrations.AddIndex(
            model_name='eaauthtoken',
            index=models.Index(fields=['algorithm_id'], name='authenticat_algorit_387d00_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='eaauthtoken',
            unique_together={('user', 'algorithm_id')},
        ),
        migrations.AddIndex(
            model_name='eaconnectionlog',
            index=models.Index(fields=['ea_token', 'connected_at'], name='authenticat_ea_toke_7b6a9e_idx'),
        ),
        migrations.AddIndex(
            model_name='eaconnectionlog',
            index=models.Index(fields=['connected_at'], name='authenticat_connect_44c5ee_idx'),
        ),
    ]
