# Generated by Django 5.2.4 on 2025-08-29 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_eaauthtoken_eaconnectionlog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='show_ea_statistics',
            field=models.BooleanField(default=True, help_text='Show EA activity statistics on dashboard'),
        ),
    ]
