# Generated by Django 5.2.4 on 2025-07-17 19:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MT5Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=20)),
                ('broker_name', models.CharField(max_length=100)),
                ('server', models.CharField(max_length=100)),
                ('account_type', models.CharField(choices=[('demo', 'Demo Account'), ('real', 'Real Account')], default='demo', max_length=10)),
                ('encrypted_password', models.TextField()),
                ('connection_status', models.CharField(choices=[('connected', 'Connected'), ('disconnected', 'Disconnected'), ('error', 'Connection Error'), ('pending', 'Pending Verification')], default='pending', max_length=20)),
                ('last_connected', models.DateTimeField(blank=True, null=True)),
                ('balance', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('equity', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('margin', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mt5_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'MT5 Account',
                'verbose_name_plural': 'MT5 Accounts',
                'db_table': 'mt5_accounts',
            },
        ),
        migrations.CreateModel(
            name='AlgorithmExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('algorithm_name', models.CharField(max_length=100)),
                ('execution_status', models.CharField(choices=[('running', 'Running'), ('stopped', 'Stopped'), ('paused', 'Paused'), ('error', 'Error'), ('completed', 'Completed')], default='running', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('stopped_at', models.DateTimeField(blank=True, null=True)),
                ('profit_loss', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('trades_count', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('last_heartbeat', models.DateTimeField(blank=True, null=True)),
                ('mt5_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='algorithm_executions', to='mt5_integration.mt5account')),
            ],
            options={
                'db_table': 'algorithm_executions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='MT5TradingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_start', models.DateTimeField(auto_now_add=True)),
                ('session_end', models.DateTimeField(blank=True, null=True)),
                ('trades_executed', models.IntegerField(default=0)),
                ('profit_loss', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('mt5_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trading_sessions', to='mt5_integration.mt5account')),
            ],
            options={
                'db_table': 'mt5_trading_sessions',
                'ordering': ['-session_start'],
            },
        ),
    ]
