# Generated by Django 5.2.4 on 2025-08-08 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mt5_integration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='algorithmexecution',
            name='pid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
