# Generated by Django 5.2.4 on 2025-08-24 00:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mt5_integration', '0002_algorithmexecution_pid'),
    ]

    operations = [
        migrations.AddField(
            model_name='algorithmexecution',
            name='avg_loss',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='algorithmexecution',
            name='avg_win',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='algorithmexecution',
            name='current_drawdown',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='algorithmexecution',
            name='current_positions',
            field=models.JSONField(default=list, help_text='Current open positions'),
        ),
        migrations.AddField(
            model_name='algorithmexecution',
            name='daily_pnl',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='algorithmexecution',
            name='emergency_stops',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='algorithmexecution',
            name='last_trade_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='algorithmexecution',
            name='losing_trades',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='algorithmexecution',
            name='max_drawdown',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='algorithmexecution',
            name='performance_metrics',
            field=models.JSONField(default=dict, help_text='Real-time performance data'),
        ),
        migrations.AddField(
            model_name='algorithmexecution',
            name='positions_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='algorithmexecution',
            name='profit_factor',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='algorithmexecution',
            name='risk_violations',
            field=models.JSONField(default=list, help_text='Risk rule violations'),
        ),
        migrations.AddField(
            model_name='algorithmexecution',
            name='sharpe_ratio',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='algorithmexecution',
            name='symbol',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='algorithmexecution',
            name='win_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='algorithmexecution',
            name='winning_trades',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='TradeResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mt5_position_id', models.BigIntegerField(blank=True, help_text='MT5 position ticket', null=True)),
                ('trade_type', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=10)),
                ('symbol', models.CharField(max_length=20)),
                ('volume', models.DecimalField(decimal_places=3, max_digits=10)),
                ('open_price', models.DecimalField(decimal_places=5, max_digits=15)),
                ('close_price', models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True)),
                ('stop_loss', models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True)),
                ('take_profit', models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True)),
                ('profit_loss', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('commission', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('swap', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('opened_at', models.DateTimeField()),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('trade_status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='open', max_length=10)),
                ('signal_data', models.JSONField(default=dict, help_text='Signal generation data')),
                ('exit_reason', models.CharField(blank=True, help_text='Why trade was closed', max_length=50, null=True)),
                ('pips_profit_loss', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('risk_reward_ratio', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_results', to='mt5_integration.algorithmexecution')),
            ],
            options={
                'db_table': 'trade_results',
                'ordering': ['-opened_at'],
            },
        ),
        migrations.CreateModel(
            name='AlgorithmSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signal_type', models.CharField(choices=[('buy', 'Buy Signal'), ('sell', 'Sell Signal'), ('close', 'Close Signal'), ('modify', 'Modify Signal')], max_length=10)),
                ('symbol', models.CharField(max_length=20)),
                ('signal_strength', models.DecimalField(decimal_places=3, help_text='Signal confidence 0-1', max_digits=5)),
                ('recommended_volume', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('recommended_price', models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True)),
                ('recommended_sl', models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True)),
                ('recommended_tp', models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True)),
                ('signal_data', models.JSONField(default=dict, help_text='Technical analysis data')),
                ('market_conditions', models.JSONField(default=dict, help_text='Market state when signal generated')),
                ('signal_status', models.CharField(choices=[('generated', 'Generated'), ('executed', 'Executed'), ('failed', 'Failed to Execute'), ('ignored', 'Ignored')], default='generated', max_length=20)),
                ('execution_message', models.TextField(blank=True, null=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signals', to='mt5_integration.algorithmexecution')),
                ('trade_result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mt5_integration.traderesult')),
            ],
            options={
                'db_table': 'algorithm_signals',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.AddIndex(
            model_name='traderesult',
            index=models.Index(fields=['execution', 'opened_at'], name='trade_resul_executi_d87e9a_idx'),
        ),
        migrations.AddIndex(
            model_name='traderesult',
            index=models.Index(fields=['symbol', 'opened_at'], name='trade_resul_symbol_c93887_idx'),
        ),
        migrations.AddIndex(
            model_name='traderesult',
            index=models.Index(fields=['trade_status'], name='trade_resul_trade_s_4e1415_idx'),
        ),
        migrations.AddIndex(
            model_name='algorithmsignal',
            index=models.Index(fields=['execution', 'generated_at'], name='algorithm_s_executi_ebafd1_idx'),
        ),
        migrations.AddIndex(
            model_name='algorithmsignal',
            index=models.Index(fields=['symbol', 'generated_at'], name='algorithm_s_symbol_572aa1_idx'),
        ),
        migrations.AddIndex(
            model_name='algorithmsignal',
            index=models.Index(fields=['signal_status'], name='algorithm_s_signal__42f937_idx'),
        ),
    ]
