# Generated by Django 5.2.4 on 2025-08-06 18:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mt5_integration', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EATemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('config_schema', models.JSONField()),
                ('tier_access', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'EA Template',
                'verbose_name_plural': 'EA Templates',
                'db_table': 'ea_templates',
            },
        ),
        migrations.CreateModel(
            name='UserEAInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('config', models.JSONField()),
                ('mt5_login', models.CharField(max_length=255)),
                ('mt5_password_encrypted', models.BinaryField()),
                ('mt5_server', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ea_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectplusdatabase.eatemplate')),
                ('mt5_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mt5_integration.mt5account')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User EA Instance',
                'verbose_name_plural': 'User EA Instances',
                'db_table': 'user_ea_instances',
            },
        ),
        migrations.CreateModel(
            name='EAPerformance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stats', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_ea_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectplusdatabase.usereainstance')),
            ],
            options={
                'verbose_name': 'EA Performance',
                'verbose_name_plural': 'EA Performance',
                'db_table': 'ea_performance',
            },
        ),
    ]
