# Generated by Django 5.2.4 on 2025-08-06 18:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mt5_integration', '0001_initial'),
        ('projectplusdatabase', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usereainstance',
            unique_together={('user', 'ea_template', 'mt5_account')},
        ),
        migrations.AddIndex(
            model_name='eaperformance',
            index=models.Index(fields=['user_ea_instance'], name='ea_performa_user_ea_95376f_idx'),
        ),
        migrations.AddIndex(
            model_name='eatemplate',
            index=models.Index(fields=['name'], name='ea_template_name_8a2872_idx'),
        ),
        migrations.AddIndex(
            model_name='usereainstance',
            index=models.Index(fields=['user'], name='user_ea_ins_user_id_648b67_idx'),
        ),
        migrations.AddIndex(
            model_name='usereainstance',
            index=models.Index(fields=['ea_template'], name='user_ea_ins_ea_temp_34f7ff_idx'),
        ),
        migrations.AddIndex(
            model_name='usereainstance',
            index=models.Index(fields=['mt5_account'], name='user_ea_ins_mt5_acc_197dc4_idx'),
        ),
    ]
